/****************
   Description : Gestion des LEDs sur la BoardA
   Auteur : Sébastien FAGUET
*****************/


#ifndef BOARDA_LEDS
#define BOARDA_LEDS

#define BOARD_LED_GREEN_ON()     HAL_GPIO_WritePin(BOARD_LED_GREEN_GPIO_Port, BOARD_LED_GREEN_Pin, GPIO_PIN_RESET)
#define BOARD_LED_GREEN_OFF()    HAL_GPIO_WritePin(BOARD_LED_GREEN_GPIO_Port, BOARD_LED_GREEN_Pin, GPIO_PIN_SET)
#define BOARD_LED_GREEN_TOGGLE() BOARD_LED_GREEN_GPIO_Port->ODR ^= BOARD_LED_GREEN_Pin
     
#define BOARD_LED_RED_ON()       HAL_GPIO_WritePin(BOARD_LED_RED_GPIO_Port, BOARD_LED_RED_Pin, GPIO_PIN_RESET)
#define BOARD_LED_RED_OFF()      HAL_GPIO_WritePin(BOARD_LED_RED_GPIO_Port, BOARD_LED_RED_Pin, GPIO_PIN_SET)
#define BOARD_LED_RED_TOGGLE()   BOARD_LED_RED_GPIO_Port->ODR ^= BOARD_LED_RED_Pin
     
#define BOARD_LED_A_ON()       HAL_GPIO_WritePin(BOARD_LED_A_GPIO_Port, BOARD_LED_A_Pin, GPIO_PIN_RESET)
#define BOARD_LED_A_OFF()      HAL_GPIO_WritePin(BOARD_LED_A_GPIO_Port, BOARD_LED_A_Pin, GPIO_PIN_SET)
#define BOARD_LED_A_TOGGLE()   BOARD_LED_A_GPIO_Port->ODR ^= BOARD_LED_A_Pin
     
#define BOARD_LED_B_ON()       HAL_GPIO_WritePin(BOARD_LED_B_GPIO_Port, BOARD_LED_B_Pin, GPIO_PIN_RESET)
#define BOARD_LED_B_OFF()      HAL_GPIO_WritePin(BOARD_LED_B_GPIO_Port, BOARD_LED_B_Pin, GPIO_PIN_SET)
#define BOARD_LED_B_TOGGLE()   BOARD_LED_B_GPIO_Port->ODR ^= BOARD_LED_B_Pin
     
#define BOARD_LED_C_ON()       HAL_GPIO_WritePin(BOARD_LED_C_GPIO_Port, BOARD_LED_C_Pin, GPIO_PIN_RESET)
#define BOARD_LED_C_OFF()      HAL_GPIO_WritePin(BOARD_LED_C_GPIO_Port, BOARD_LED_C_Pin, GPIO_PIN_SET)
#define BOARD_LED_C_TOGGLE()   BOARD_LED_C_GPIO_Port->ODR ^= BOARD_LED_C_Pin
     
#define BOARD_LED_D_ON()       HAL_GPIO_WritePin(BOARD_LED_D_GPIO_Port, BOARD_LED_D_Pin, GPIO_PIN_RESET)
#define BOARD_LED_D_OFF()      HAL_GPIO_WritePin(BOARD_LED_D_GPIO_Port, BOARD_LED_D_Pin, GPIO_PIN_SET)
#define BOARD_LED_D_TOGGLE()   BOARD_LED_D_GPIO_Port->ODR ^= BOARD_LED_D_Pin
     
#define BOARD_LED_E_ON()       HAL_GPIO_WritePin(BOARD_LED_E_GPIO_Port, BOARD_LED_E_Pin, GPIO_PIN_RESET)
#define BOARD_LED_E_OFF()      HAL_GPIO_WritePin(BOARD_LED_E_GPIO_Port, BOARD_LED_E_Pin, GPIO_PIN_SET)
#define BOARD_LED_E_TOGGLE()   BOARD_LED_E_GPIO_Port->ODR ^= BOARD_LED_E_Pin
     
#define BOARD_LED_F_ON()       HAL_GPIO_WritePin(BOARD_LED_F_GPIO_Port, BOARD_LED_F_Pin, GPIO_PIN_RESET)
#define BOARD_LED_F_OFF()      HAL_GPIO_WritePin(BOARD_LED_F_GPIO_Port, BOARD_LED_F_Pin, GPIO_PIN_SET)
#define BOARD_LED_F_TOGGLE()   BOARD_LED_F_GPIO_Port->ODR ^= BOARD_LED_F_Pin
     
#define BOARD_LED_G_ON()       HAL_GPIO_WritePin(BOARD_LED_G_GPIO_Port, BOARD_LED_G_Pin, GPIO_PIN_RESET)
#define BOARD_LED_G_OFF()      HAL_GPIO_WritePin(BOARD_LED_G_GPIO_Port, BOARD_LED_G_Pin, GPIO_PIN_SET)
#define BOARD_LED_G_TOGGLE()   BOARD_LED_G_GPIO_Port->ODR ^= BOARD_LED_G_Pin
     
#define BOARD_LED_H_ON()       HAL_GPIO_WritePin(BOARD_LED_H_GPIO_Port, BOARD_LED_H_Pin, GPIO_PIN_RESET)
#define BOARD_LED_H_OFF()      HAL_GPIO_WritePin(BOARD_LED_H_GPIO_Port, BOARD_LED_H_Pin, GPIO_PIN_SET)
#define BOARD_LED_H_TOGGLE()   BOARD_LED_H_GPIO_Port->ODR ^= BOARD_LED_H_Pin
     
#define BOARD_LED_ALL_OFF()      BOARD_LED_RED_OFF(); BOARD_LED_GREEN_OFF(); BOARD_LED_A_OFF(); BOARD_LED_B_OFF(); BOARD_LED_C_OFF(); BOARD_LED_D_OFF(); BOARD_LED_E_OFF(); BOARD_LED_F_OFF(); BOARD_LED_G_OFF(); BOARD_LED_H_OFF();

#endif
